[platformio]
default_envs = earth, sat_a, relay_b, relay_c
src_dir = vorthyx_node

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -D WIFI_CHANNEL=1

[env:earth]
build_flags = ${env.build_flags} -D NODE_ID=0

[env:sat_a]
build_flags = ${env.build_flags} -D NODE_ID=1

[env:relay_b]
build_flags = ${env.build_flags} -D NODE_ID=2

[env:relay_c]
build_flags = ${env.build_flags} -D NODE_ID=3
